name: Trivy Vulnerability Scan

on:
  push:
    branches: [ master ] # or 'main' if your branch is named main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t devsecops-demo .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: devsecops-demo
        format: table
        exit-code: 1
        ignore-unfixed: true
